apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodepulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodepulse
  template:
    metadata:
      labels:
        app: nodepulse
    spec:
      containers:
        - name: nodepulse
          image: nodepulse:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodepulse-secrets
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: nodepulse-secrets
                  key: MONGO_URI
            - name: CHAIN_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: nodepulse-secrets
                  key: CHAIN_RPC_URL
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
