apiVersion: v1
kind: Secret
metadata:
  name: nodepulse-secrets
type: Opaque
data:
  # Base64-encoded values. Example generation:
  # echo -n "your_jwt_secret" | base64
  JWT_SECRET: ""
  MONGO_URI: ""
  CHAIN_RPC_URL: ""
  SIDECAR_KEY_SECRET: ""
